/**
 * Node of a binary search tree storing {@link Physical} key-value pairs.
 *
 * <p>The subtree is ordered according to a {@link PhysicalComparator}.
 * Search and insertion decisions use this order relation.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public class PhysicalPhysicalTreeMapNodeNonEmpty implements PhysicalPhysicalTreeMapNode {

    private Physical key;
    private Physical value;

    private PhysicalPhysicalTreeMapNode left;
    private PhysicalPhysicalTreeMapNode right;

    /**
     * Creates a new node with the specified key-value pair.
     *
     * @param key the key stored in this node; {@code key != null}
     * @param value the associated value
     */
    public PhysicalPhysicalTreeMapNodeNonEmpty(Physical key, Physical value) {

        this.key = key;
        this.value = value;
        left = right = PhysicalPhysicalTreeMapNodeEmpty.EMPTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getLeft() {
        return left;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getRight() {
        return right;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Physical getKey() {
        return key;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Physical getValue() {
        return value;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode put(Physical key, Physical value, PhysicalComparator comparator, Physical[] oldValueBox, boolean[] insertedBox) {

        if (this.key.equals(key)) {
            oldValueBox[0] = this.value;
            insertedBox[0] = false;
            this.value = value;
            return this;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            left = left.put(key, value, comparator, oldValueBox, insertedBox);
        } else {
            right = right.put(key, value, comparator, oldValueBox, insertedBox);
        }
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Physical get(Physical key, PhysicalComparator comparator) {

        if (this.key.equals(key)) {
            return value;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            return left.get(key, comparator);
        } else {
            return right.get(key, comparator);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean containsKey(Physical key, PhysicalComparator comparator) {

        if (this.key.equals(key)) {
            return true;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            return left.containsKey(key, comparator);
        } else {
            return right.containsKey(key, comparator);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean containsValue(Physical value) {

        if (this.value == null ? value == null : this.value.equals(value)) {
            return true;
        }

        return left.containsValue(value) || right.containsValue(value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void fillKeys(PhysicalSet result) {

        left.fillKeys(result);
        result.add(key);
        right.fillKeys(result);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void fillValues(PhysicalSet result) {

        if (value != null) {
            result.add(value);
        }

        left.fillValues(result);
        right.fillValues(result);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toIndentedString(String indent) {

        String result = indent + key.toString() + " -> " + value + "\n";

        result += left.toIndentedString(indent + "  ");
        result += right.toIndentedString(indent + "  ");

        return result;
    }
}