/**
 * Represents a celestial body with a name and a radius. Celestial bodies are planets, stars, or other astronomical
 * bodies.
 * All objects of type CelestialBody have a constant position of (0.0, 0.0).
 *
 */

/*DO NOT EDIT THIS FILE!*/

public class CelestialBody implements Physical
{

    private final String name;
    private final double radius;
    private final Vector2D position;

    /**
     * Creates a new celestial body with the specified name and radius.
     *
     * @param name the name of the body; must not be {@code null}
     * @param radius the radius of the body in km; radius >= 0.
     */
    public CelestialBody(String name, double radius) {

        this.name = name;
        this.radius = radius;
        this.position = new Vector2D(0.0, 0.0);
    }

    /**
     * Returns the current position of this object.
     *
     * <p>The returned vector represents the center of the object in the
     * two-dimensional world.</p>
     *
     * @return the position of this object; never {@code null}
     */
    @Override
    public Vector2D getPosition() {
        return this.position;
    }

    /**
     * Returns the radius of this object.
     *
     * <p>The radius describes the spatial extent of the object around its
     * center position. The returned value must not be negative.</p>
     *
     * @return the radius of this object; {@code getRadius() >= 0.0}
     */
    @Override
    public double getRadius() {
        return this.radius;
    }

    /**
     * Returns a string representation of this celestial body.
     *
     * <p>The representation includes the name of the body followed by its radius in parentheses.
     *
     * Example: "Saturn (58232 km)"
     *
     * @return a string representation in the format "{name} ({radius} km)"
     */
    @Override
    public String toString() {
        return this.name + " (" + String.format("%.0f", radius) + " km)";
    }

}