/**
 * Node of a singly linked list storing a {@link Physical} element.
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
class PhysicalSinglyLinkedListNode {

    /** The stored element. */
    private Physical value;

    /** Reference to the next node in the list, or {@code null} if this is the last node. */
    private PhysicalSinglyLinkedListNode next;

    /**
     * Creates a new node with the specified value and successor.
     *
     * @param value the stored element
     * @param next the next node, or {@code null} if none
     */
    public PhysicalSinglyLinkedListNode(Physical value, PhysicalSinglyLinkedListNode next) {
        this.value = value;
        this.next = next;
    }

    /**
     * Returns the stored element.
     *
     * @return the stored {@link Physical} object
     */
    public Physical getValue() {
        return value;
    }

    /**
     * Returns the next node in the list.
     *
     * @return the next node, or {@code null} if this is the last node
     */
    public PhysicalSinglyLinkedListNode getNext() {
        return next;
    }

    /**
     * Sets the next node reference.
     *
     * @param next the new successor node (may be {@code null})
     */
    public void setNext(PhysicalSinglyLinkedListNode next) {
        this.next = next;
    }
}