/**
 * Represents a celestial body with a position and a radius. Celestial bodies are planets, stars, or other astronomical
 * bodies.
 *
 */

/*DO NOT EDIT THIS FILE!*/

public class CelestialBody implements Physical
{

    private final double radius;
    private final Vector2D position;

    /**
     * Creates a new celestial body with the specified radius.
     *
     * @param position the position in 2D space; must not be {@code null}
     * @param radius the radius of the body in km; radius >= 0.
     */
    public CelestialBody(Vector2D position, double radius) {

        this.radius = radius;
        this.position = position;
    }

    /**
     * Returns the current position of this object.
     *
     * <p>The returned vector represents the center of the object in the
     * two-dimensional world.</p>
     *
     * @return the position of this object; never {@code null}
     */
    @Override
    public Vector2D getPosition() {
        return this.position;
    }

    /**
     * Returns the radius of this object.
     *
     * <p>The radius describes the spatial extent of the object around its
     * center position. The returned value must not be negative.</p>
     *
     * @return the radius of this object; {@code getRadius() >= 0.0}
     */
    @Override
    public double getRadius() {
        return this.radius;
    }

}