/**
 * Singly linked list with elements of type {@link Physical}.
 *
 * <p>The list is implemented as a recursive data structure with one node
 * for each element in the list.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
public class PhysicalSinglyLinkedList {

    private PhysicalSinglyLinkedListNode head;
    private int size;

    /**
     * Creates an empty list.
     */
    public PhysicalSinglyLinkedList() {

        this.head = null;
        this.size = 0;
    }

    /**
     * Creates a new list that is a copy of the specified list. Later changes of
     * {@code this} (like adding or removing elements) will not affect {@code list} and
     * vice versa.
     *
     * <p>The new list contains the same elements and in the same order
     * as {@code list}.</p>
     *
     * @param list the list to copy; {@code list != null}
     */
    public PhysicalSinglyLinkedList(PhysicalSinglyLinkedList list) {

        this();
        PhysicalSinglyLinkedListNode current = list.head;
        PhysicalSinglyLinkedListNode last = null;

        while (current != null) {
            PhysicalSinglyLinkedListNode n = new PhysicalSinglyLinkedListNode(current.getValue(), null);
            if (this.head == null) {
                this.head = n;
            } else {
                last.setNext(n);
            }
            last = n;
            current = current.getNext();
            this.size++;
        }
    }

    /**
     * Adds an element at the head of the list.
     *
     * @param p the element to add
     */
    public void addFirst(Physical p) {

        head = new PhysicalSinglyLinkedListNode(p, head);
        size++;
    }

    /**
     * Adds an element at the end of the list.
     *
     * @param p the element to add
     */
    public void addLast(Physical p) {

        if (head == null) {
            head = new PhysicalSinglyLinkedListNode(p, null);
        } else {
            PhysicalSinglyLinkedListNode current = head;
            while (current.getNext() != null) {
                current = current.getNext();
            }
            current.setNext(new PhysicalSinglyLinkedListNode(p, null));
        }
        size++;
    }

    /**
     * Adds an element at the specified position in the list.
     *
     * <p>If {@code index == 0}, the element is inserted at the head of the list.
     * If {@code index == size()}, the element is inserted at the end of the list.
     * All elements currently stored at positions greater than or equal to
     * {@code index} are shifted by one position toward the end of the list.</p>
     *
     * @param index the position at which the element is to be inserted;
     *              {@code 0 <= index <= size()}
     * @param p the element to add
     */
    public void add(int index, Physical p) {

        if (index == 0) {
            addFirst(p);
            return;
        }

        PhysicalSinglyLinkedListNode prev = nodeAt(index - 1);
        prev.setNext(new PhysicalSinglyLinkedListNode(p, prev.getNext()));
        size++;
    }

    /**
     * Removes and returns the head element of the list.
     *
     * <p>This method removes the first element of the list.</p>
     *
     * @return the first element in the list, or {@code null} if {@code size() == 0}
     */
    public Physical pollFirst() {

        if (head == null) {
            return null;
        }

        Physical result = head.getValue();
        head = head.getNext();
        size--;
        return result;
    }

    /**
     * Removes and returns the last element of the list.
     *
     * <p>This method removes the last element of the list.</p>
     *
     * @return the last element in the list, or {@code null} if {@code size() == 0}
     */
    public Physical pollLast() {

        if (head == null) {
            return null;
        }
        if (head.getNext() == null) {
            return pollFirst();
        }

        PhysicalSinglyLinkedListNode prev = head;
        PhysicalSinglyLinkedListNode current = head.getNext();
        while (current.getNext() != null) {
            prev = current;
            current = current.getNext();
        }

        prev.setNext(null);
        size--;
        return current.getValue();
    }

    /**
     * Returns the head element of the list without removing it.
     *
     * <p>The list remains unchanged after this operation.</p>
     *
     * @return the first element in the list, or {@code null} if {@code size() == 0}
     */
    public Physical peekFirst() {

        return head == null ? null : head.getValue();
    }

    /**
     * Returns the last element of the list without removing it.
     *
     * <p>The list remains unchanged after this operation.</p>
     *
     * @return the last element in the list, or {@code null} if {@code size() == 0}
     */
    public Physical peekLast() {

        if (head == null) {
            return null;
        }

        PhysicalSinglyLinkedListNode current = head;
        while (current.getNext() != null) {
            current = current.getNext();
        }
        return current.getValue();
    }

    /**
     * Returns whether this list contains the specified element (identical to `p`).
     *
     * @param p the element to search for
     * @return {@code true} if present, otherwise {@code false}
     */
    public boolean contains(Physical p) {

        PhysicalSinglyLinkedListNode current = head;
        while (current != null) {
            if (current.getValue() == p) {
                return true;
            }
            current = current.getNext();
        }
        return false;
    }

    /**
     * Returns the element at the specified position in the list.
     *
     * <p>The first element has index {@code 0}.</p>
     *
     * @param index the index of the element to return;
     *              {@code 0 <= index < size()}
     * @return the element at the specified position
     */
    public Physical get(int index) {

        return nodeAt(index).getValue();
    }

    /**
     * Removes and returns the element at the specified position in the list.
     *
     * <p>All elements following the removed element are shifted by one position
     * toward the head of the list.</p>
     *
     * @param index the index of the element to remove;
     *              {@code 0 <= index < size()}
     * @return the removed element
     */
    public Physical remove(int index) {

        if (index == 0) {
            return pollFirst();
        }

        PhysicalSinglyLinkedListNode prev = nodeAt(index - 1);
        PhysicalSinglyLinkedListNode removed = prev.getNext();
        prev.setNext(removed.getNext());
        size--;
        return removed.getValue();
    }

    /**
     * Returns whether this list contains no elements.
     *
     * @return {@code true} if {@code size() == 0}, {@code false} otherwise
     */
    public boolean isEmpty() {

        return size == 0;
    }

    /**
     * Returns the number of elements currently stored in the list.
     *
     * @return the current size of the list
     */
    public int size() {

        return size;
    }

    /**
     * Removes all elements from the list.
     */
    public void clear() {

        this.head = null;
        this.size = 0;
    }

    private PhysicalSinglyLinkedListNode nodeAt(int index) {
        PhysicalSinglyLinkedListNode current = head;
        for (int i = 0; i < index; i++) {
            current = current.getNext();
        }
        return current;
    }
}