/**
 * Node of a doubly linked list storing a {@link Physical} element.
 *
 * <p>Each node contains a value and references to its predecessor
 * and successor in the list. The first node has {@code prev == null},
 * and the last node has {@code next == null}.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
class PhysicalDoublyLinkedListNode {

    private final Physical value;
    private PhysicalDoublyLinkedListNode next;
    private PhysicalDoublyLinkedListNode prev;

    /**
     * Creates a new node storing the specified element and linking it
     * to the given predecessor and successor nodes.
     *
     * @param value the element to store; {@code value != null}
     * @param prev the previous node in the list (may be {@code null})
     * @param next the next node in the list (may be {@code null})
     */
    public PhysicalDoublyLinkedListNode(Physical value, PhysicalDoublyLinkedListNode prev, PhysicalDoublyLinkedListNode next) {
        this.value = value;
        this.prev = prev;
        this.next = next;
    }

    /**
     * Returns the stored element.
     *
     * @return the stored {@link Physical} object
     */
    public Physical getValue() {
        return value;
    }

    /**
     * Returns the next node in the list.
     *
     * @return the next node, or {@code null} if this is the last node
     */
    public PhysicalDoublyLinkedListNode getNext() {
        return next;
    }

    /**
     * Sets the next node reference.
     *
     * @param next the new successor node (may be {@code null})
     */
    public void setNext(PhysicalDoublyLinkedListNode next) {
        this.next = next;
    }

    /**
     * Returns the previous node in the list.
     *
     * @return the previous node, or {@code null} if this is the first node
     */
    public PhysicalDoublyLinkedListNode getPrev() {
        return prev;
    }

    /**
     * Sets the previous node reference.
     *
     * @param prev the new predecessor node (may be {@code null})
     */
    public void setPrev(PhysicalDoublyLinkedListNode prev) {
        this.prev = prev;
    }
}