/**
 * Node of a k-d tree storing a {@link Physical} object.
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
class PhysicalKDTreeSetNode {

    private final Physical value;
    private PhysicalKDTreeSetNode left;
    private PhysicalKDTreeSetNode right;

    /**
     * Creates a new node storing the specified physical object.
     *
     * @param value the object to store; {@code value != null}
     */
    public PhysicalKDTreeSetNode(Physical value) {
        this.value = value;
    }

    /**
     * Inserts the specified physical object into the subtree rooted at this node.
     *
     * @param p the object to insert; {@code p != null}
     * @param depth the current depth in the tree (root starts at depth 1)
     */
    public boolean add(Physical p, int depth) {

        if (p == value) return false;

        int axis = depth % 2;

        if (compare(p, value, axis) < 0) {
            if (left == null) {
                left = new PhysicalKDTreeSetNode(p);
            } else {
                return left.add(p, depth + 1);
            }
        } else { //includes compare(p, value, axis) == 0
            if (right == null) {
                right = new PhysicalKDTreeSetNode(p);
            } else {
                return right.add(p, depth + 1);
            }
        }

        return true;
    }

    /**
     * Returns whether this subtree contains the specified object by identity.
     *
     * @param p the object to search for; {@code p != null}
     * @param depth the current depth in the tree
     * @return {@code true} if the exact object reference is stored in this subtree
     */
    public boolean contains(Physical p, int depth) {

        if (value == p) {
            return true;
        }

        int cmp = compare(p, value, depth % 2);

        if (cmp < 0) {
            return left != null && left.contains(p, depth + 1);
        } else {
            return right != null && right.contains(p, depth + 1);
        }
    }

    /**
     * Performs a circular range query on the subtree rooted at this node.
     *
     * <p>All {@link Physical} objects whose center lies within the specified
     * radius around the given query center are added to {@code result}.</p>
     *
     * @param center the center of the query circle; {@code center != null}
     * @param radius the radius of the query circle; {@code radius >= 0}
     * @param radiusSquared the squared radius (used to avoid computing square roots)
     * @param depth the current depth in the tree (root starts at depth 1)
     * @param result the list to which matching objects are added; {@code result != null}
     */
    public void rangeQuery(Vector2D center,
                           double radius,
                           double radiusSquared,
                           int depth,
                           PhysicalDoublyLinkedRingList result) {

        Vector2D p = value.getPosition();

        double dx = p.getX() - center.getX();
        double dy = p.getY() - center.getY();
        double dist2 = dx * dx + dy * dy;

        if (dist2 <= radiusSquared) {
            result.addLast(value);
        }

        int axis = depth % 2;

        double centerCoord = axis == 1 ? center.getX() : center.getY();
        double nodeCoord = axis == 1 ? p.getX() : p.getY();

        if (centerCoord - radius <= nodeCoord && left != null) {
            left.rangeQuery(center, radius, radiusSquared, depth + 1, result);
        }

        if (centerCoord + radius >= nodeCoord && right != null) {
            right.rangeQuery(center, radius, radiusSquared, depth + 1, result);
        }
    }

    /**
     * Performs an axis-aligned rectangular range query on the subtree rooted at this node.
     *
     * <p>All {@link Physical} objects whose center lies within the specified
     * rectangle are added to {@code result}. The rectangle is defined by its
     * minimum and maximum coordinates.</p>
     *
     * @param minX the minimum x-coordinate of the query rectangle
     * @param minY the minimum y-coordinate of the query rectangle
     * @param maxX the maximum x-coordinate of the query rectangle
     * @param maxY the maximum y-coordinate of the query rectangle
     * @param depth the current depth in the tree (root starts at depth 1)
     * @param result the list to which matching objects are added; {@code result != null}
     */
    public void rangeQueryRectangle(double minX,
                                    double minY,
                                    double maxX,
                                    double maxY,
                                    int depth,
                                    PhysicalDoublyLinkedRingList result) {

        Vector2D p = value.getPosition();
        double x = p.getX();
        double y = p.getY();

        if (x >= minX && x <= maxX && y >= minY && y <= maxY) {
            result.addLast(value);
        }

        int axis = depth % 2;

        if (axis == 1) {
            if (minX <= x && left != null) {
                left.rangeQueryRectangle(minX, minY, maxX, maxY, depth + 1, result);
            }
            if (maxX >= x && right != null) {
                right.rangeQueryRectangle(minX, minY, maxX, maxY, depth + 1, result);
            }
        } else {
            if (minY <= y && left != null) {
                left.rangeQueryRectangle(minX, minY, maxX, maxY, depth + 1, result);
            }
            if (maxY >= y && right != null) {
                right.rangeQueryRectangle(minX, minY, maxX, maxY, depth + 1, result);
            }
        }
    }

    /**
     * Returns the maximum radius among all stored objects in this subtree.
     *
     * @return the maximum radius in this subtree.
     */
    public double getMaxStoredRadius() {

        double here = value.getRadius();
        double leftMax = left == null ? 0.0 : left.getMaxStoredRadius();
        double rightMax = right == null ? 0.0 : right.getMaxStoredRadius();

        return Math.max(here, Math.max(leftMax, rightMax));
    }

    /**
     * Compares two {@link Physical} objects with respect to the specified axis.
     *
     * <p>The comparison is based on the coordinate of the objects' positions
     * along the selected axis:</p>
     * <ul>
     *   <li>If {@code axis == 1}, the x-coordinate is compared.</li>
     *   <li>Otherwise, the y-coordinate is compared.</li>
     * </ul>
     *
     * <p>The method returns a negative value if {@code a} is smaller than {@code b},
     * a positive value if {@code a} is greater than {@code b}, and {@code 0} if both
     * coordinates are equal.</p>
     *
     * @param a the first object; {@code a != null}
     * @param b the second object; {@code b != null}
     * @param axis the axis used for comparison (1 for x-axis, otherwise y-axis)
     * @return a negative value if {@code a < b}, a positive value if {@code a > b},
     *         or {@code 0} if both are equal with respect to the selected axis
     */
    private int compare(Physical a, Physical b, int axis) {

        double a1 = axis == 1 ? a.getPosition().getX() : a.getPosition().getY();
        double b1 = axis == 1 ? b.getPosition().getX() : b.getPosition().getY();

        if (a1 < b1) return -1;
        if (a1 > b1) return 1;

        return 0;
    }
}