/**
 * Node of a doubly linked circular list.
 *
 * <p>The NIL node has {@code value == null}.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
class PhysicalDoublyLinkedRingListNode {

    private final Physical value;
    private PhysicalDoublyLinkedRingListNode next;
    private PhysicalDoublyLinkedRingListNode prev;

    /**
     * Creates a new node storing the specified element.
     *
     * @param value the element to store (may be {@code null} for the NIL node)
     */
    public PhysicalDoublyLinkedRingListNode(Physical value) {
        this.value = value;
    }

    /**
     * Returns the stored element.
     *
     * @return the stored {@link Physical} object (or {@code null} for the NIL node)
     */
    public Physical getValue() {
        return value;
    }

    /**
     * Returns the next node in the list.
     *
     * @return the next node
     */
    public PhysicalDoublyLinkedRingListNode getNext() {
        return next;
    }

    /**
     * Sets the next node reference.
     *
     * @param next the new successor node
     */
    public void setNext(PhysicalDoublyLinkedRingListNode next) {
        this.next = next;
    }

    /**
     * Returns the previous node in the list.
     *
     * @return the previous node
     */
    public PhysicalDoublyLinkedRingListNode getPrev() {
        return prev;
    }

    /**
     * Sets the previous node reference.
     *
     * @param prev the new predecessor node
     */
    public void setPrev(PhysicalDoublyLinkedRingListNode prev) {
        this.prev = prev;
    }
}