/**
 * Doubly linked circular list with sentinel (NIL) node
 * and elements of type {@link Physical}.
 *
 * <p>The list is implemented as a doubly linked ring. A dedicated NIL node
 * is always present and simplifies all insert/remove operations:
 * for an empty list, {@code nil.next == nil} and {@code nil.prev == nil}.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
public class PhysicalDoublyLinkedRingList {

    private final PhysicalDoublyLinkedRingListNode nil;
    private int size;

    /**
     * Creates an empty list.
     */
    public PhysicalDoublyLinkedRingList() {

        nil = new PhysicalDoublyLinkedRingListNode(null);
        nil.setNext(nil);
        nil.setPrev(nil);
        size = 0;
    }

    /**
     * Creates a new list that is a copy of the specified list.
     * Later changes of {@code this} do not affect {@code list} and vice versa.
     *
     * @param list the list to copy; {@code list != null}
     */
    public PhysicalDoublyLinkedRingList(PhysicalDoublyLinkedRingList list) {

        this();

        PhysicalDoublyLinkedRingListNode current = list.nil.getNext();
        while (current != list.nil) {
            addLast(current.getValue());
            current = current.getNext();
        }
    }

    /**
     * Adds an element at the head of the list.
     *
     * @param p the element to add
     */
    public void addFirst(Physical p) {

        insertBetween(p, nil, nil.getNext());
    }

    /**
     * Adds an element at the end of the list.
     *
     * @param p the element to add
     */
    public void addLast(Physical p) {

        insertBetween(p, nil.getPrev(), nil);
    }

    /**
     * Adds an element at the specified position in the list.
     *
     * <p>If {@code index == 0}, the element is inserted at the head of the list.
     * If {@code index == size()}, the element is inserted at the end of the list.</p>
     *
     * @param index the insertion index; {@code 0 <= index <= size()}
     * @param p the element to add
     */
    public void add(int index, Physical p) {

        if (index == size) {
            addLast(p);
            return;
        }

        PhysicalDoublyLinkedRingListNode nextNode = nodeAt(index);
        insertBetween(p, nextNode.getPrev(), nextNode);
    }

    /**
     * Removes and returns the head element of the list.
     *
     * @return the first element, or {@code null} if the list is empty
     */
    public Physical pollFirst() {

        if (isEmpty()) {
            return null;
        }
        return unlink(nil.getNext());
    }

    /**
     * Removes and returns the last element of the list.
     *
     * @return the last element, or {@code null} if the list is empty
     */
    public Physical pollLast() {

        if (isEmpty()) {
            return null;
        }
        return unlink(nil.getPrev());
    }

    /**
     * Returns the head element without removing it.
     *
     * @return the first element, or {@code null} if the list is empty
     */
    public Physical peekFirst() {

        return isEmpty() ? null : nil.getNext().getValue();
    }

    /**
     * Returns the last element without removing it.
     *
     * @return the last element, or {@code null} if the list is empty
     */
    public Physical peekLast() {

        return isEmpty() ? null : nil.getPrev().getValue();
    }

    /**
     * Returns whether this list contains the specified element (identical to `p`).
     *
     * @param p the element to search for
     * @return {@code true} if present, otherwise {@code false}
     */
    public boolean contains(Physical p) {

        PhysicalDoublyLinkedRingListNode current = nil.getNext();

        while (current != nil) {
            if (current.getValue().equals(p)) {
                return true;
            }
            current = current.getNext();
        }

        return false;
    }

    /**
     * Returns the element at the specified position.
     *
     * @param index the index; {@code 0 <= index < size()}
     * @return the element at the specified position
     */
    public Physical get(int index) {

        return nodeAt(index).getValue();
    }

    /**
     * Removes and returns the element at the specified position.
     *
     * @param index the index; {@code 0 <= index < size()}
     * @return the removed element
     */
    public Physical remove(int index) {

        return unlink(nodeAt(index));
    }

    /**
     * Removes all elements from the list.
     */
    public void clear() {

        nil.setNext(nil);
        nil.setPrev(nil);
        size = 0;
    }

    /**
     * Returns whether this list contains no elements.
     *
     * @return {@code true} if empty, otherwise {@code false}
     */
    public boolean isEmpty() {

        return size == 0;
    }

    /**
     * Returns the number of elements currently stored in the list.
     *
     * @return the current size
     */
    public int size() {

        return size;
    }

    private void insertBetween(Physical value, PhysicalDoublyLinkedRingListNode prev, PhysicalDoublyLinkedRingListNode next) {
        PhysicalDoublyLinkedRingListNode node = new PhysicalDoublyLinkedRingListNode(value);

        node.setPrev(prev);
        node.setNext(next);
        prev.setNext(node);
        next.setPrev(node);

        size++;
    }

    private Physical unlink(PhysicalDoublyLinkedRingListNode node) {
        node.getPrev().setNext(node.getNext());
        node.getNext().setPrev(node.getPrev());

        size--;

        return node.getValue();
    }

    private PhysicalDoublyLinkedRingListNode nodeAt(int index) {
        if (index < size / 2) {
            PhysicalDoublyLinkedRingListNode current = nil.getNext();
            for (int i = 0; i < index; i++) {
                current = current.getNext();
            }
            return current;
        } else {
            PhysicalDoublyLinkedRingListNode current = nil.getPrev();
            for (int i = size - 1; i > index; i--) {
                current = current.getPrev();
            }
            return current;
        }
    }
}