/**
 * A two-dimensional k-d tree for spatial indexing of {@link Physical} objects.
 *
 * <p>This data structure organizes physical objects according to their positions
 * in a two-dimensional space. It allows efficient spatial queries such as
 * finding all objects within a given radius or region.
 * The structure alternates between splitting along the x-axis and y-axis at
 * successive levels.</p>
 *
 * <p>The tree does not store {@code null} elements.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE
 */
public class PhysicalKDTreeSet {

    private PhysicalKDTreeSetNode root;
    private int size;

    /**
     * Creates an empty k-d tree.
     */
    public PhysicalKDTreeSet() {

        root = null;
        size = 0;
    }

    /**
     * Creates a new k-d tree containing all elements of the given array.
     *
     * @param physicals the source array;
     *                  {@code physicals != null && physicals[i] != null} for all valid i
     */
    public PhysicalKDTreeSet(Physical[] physicals) {

        add(physicals);
    }

    /**
     * Inserts the specified physical object into this k-d tree. If `p` is already
     * contained (see method `contains`) in this tree, the method does nothing.
     *
     * <p>The new object is inserted according to the recursive splitting rule
     * of the k-d tree. At odd depths, objects are compared by x-coordinate;
     * at even depths, they are compared by y-coordinate.</p>
     *
     * @param p the object to insert; {@code p != null}
     */
    public void add(Physical p) {

        if (root == null) {
            root = new PhysicalKDTreeSetNode(p);
            size++;
        } else {
            if (root.add(p, 1)) {
                size++;
            }
        }
    }

    /**
     * Adds the physical objects of the specified array to this tree. Objects that are already
     * contained in this tree (see method `contains`) are not added.
     *
     * @param physicals the source array;
     *                  {@code physicals != null && physicals[i] != null} for all valid i
     */
    public void add(Physical[] physicals) {

        for (Physical p: physicals) {
            add(p);
        }
    }

    /**
     * Returns whether this tree contains the specified physical object.
     *
     * <p>This method checks for object identity, not structural equality.
     * That is, it returns {@code true} if and only if the exact same object
     * reference (using {@code ==}) is stored in this tree.</p>
     *
     * @param p the object to search for; {@code p != null}
     * @return {@code true} if {@code p} is contained in this tree,
     *         otherwise {@code false}
     */
    public boolean contains(Physical p) {

        if (root == null) return false;

        return root.contains(p, 1);
    }

    /**
     * Returns the number of elements currently stored in this tree.
     *
     * @return the number of stored elements
     */
    public int size() {
        return size;
    }

    /**
     * Removes all elements from this tree.
     *
     * <p>After this operation, {@link #isEmpty()} returns {@code true}.</p>
     */
    public void clear() {

        root = null;
        size = 0;
    }

    /**
     * Returns whether this tree contains no elements.
     *
     * @return {@code true} if {@code size() == 0}, otherwise {@code false}
     */
    public boolean isEmpty() {
        return size == 0;
    }

    /**
     * Returns all physical objects whose center lies within the specified radius
     * around the given position.
     *
     * <p>This method performs a circular range query. Only objects whose center
     * is within the given distance from {@code center} are returned.</p>
     *
     * <p>The returned list is independent of the internal structure of the tree.
     * Modifying the list does not affect the tree.</p>
     *
     * @param center the query center; {@code center != null}
     * @param radius the query radius; {@code radius >= 0}
     * @return a list containing all matching objects (possibly empty)
     */
    public PhysicalDoublyLinkedRingList rangeQuery(Vector2D center, double radius) {

        PhysicalDoublyLinkedRingList result = new PhysicalDoublyLinkedRingList();
        if (root != null) {
            root.rangeQuery(center, radius, radius * radius, 1, result);
        }
        return result;
    }

    /**
     * Returns all physical objects whose center lies within the specified
     * axis-aligned rectangle.
     *
     * <p>The rectangle is defined by its minimum and maximum coordinates.</p>
     *
     * @param minX the minimum x-coordinate
     * @param minY the minimum y-coordinate
     * @param maxX the maximum x-coordinate
     * @param maxY the maximum y-coordinate
     * @return a list containing all matching objects (possibly empty)
     */
    public PhysicalDoublyLinkedRingList rangeQuery(double minX, double minY, double maxX, double maxY) {

        PhysicalDoublyLinkedRingList result = new PhysicalDoublyLinkedRingList();
        if (root != null) {
            root.rangeQueryRectangle(minX, minY, maxX, maxY, 1, result);
        }
        return result;
    }

    /**
     * Returns all physical objects that intersect a hypothetical circle
     * defined by the specified position and radius.
     *
     * <p>This method first performs a spatial range query to collect nearby
     * objects, and then filters them using geometric intersection.</p>
     *
     * <p>This method is useful for collision detection at a candidate position.</p>
     *
     * @param position the center of the hypothetical object; {@code position != null}
     * @param radius the radius of the hypothetical object; {@code radius >= 0}
     * @return a list of all intersecting objects (possibly empty)
     */
    public PhysicalDoublyLinkedRingList intersectingAt(Vector2D position, double radius) {

        PhysicalDoublyLinkedRingList nearby =
                rangeQuery(position, radius + getMaxStoredRadius());

        PhysicalDoublyLinkedRingList result = new PhysicalDoublyLinkedRingList();

        for (int i = 0; i < nearby.size(); i++) {
            Physical p = nearby.get(i);
            if (p.intersects(position, radius)) {
                result.addLast(p);
            }
        }

        return result;
    }

    /**
     * Returns the maximum radius among all stored physical objects.
     */
    public double getMaxStoredRadius() {

        return root == null ? 0.0 : root.getMaxStoredRadius();
    }
}