/**
 * Represents a simplified customer class that stores the total value of the customer's shopping cart ({@code cartValue}).
 */

/*DO NOT EDIT THIS FILE!*/

public class Customer {

    /**
     * The total value of the customer's shopping cart (dt. "Einkaufswagen").
     */
    private int cartValue;

    /**
     * Constructs a new Customer instance with the specified initial cart value.
     *
     * @param cartValue the initial total value of items in the customer's shopping cart.
     */
    public Customer(int cartValue) {
        this.cartValue = cartValue;
    }

    /**
     * Returns the current total value of the customer's shopping cart.
     *
     * @return the total value of items in the shopping cart.
     */
    public int getCartValue() {
        return cartValue;
    }
}