/**
 * An empty node used by {@link PhysicalPhysicalTreeMap}.
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public class PhysicalPhysicalTreeMapNodeEmpty implements PhysicalPhysicalTreeMapNode {

    // the only instance of this class
    public static final PhysicalPhysicalTreeMapNodeEmpty EMPTY = new PhysicalPhysicalTreeMapNodeEmpty();

    /**
     * Constructs an empty node.
     * No construction outside this class possible.
     */
    private PhysicalPhysicalTreeMapNodeEmpty() {}

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode put(Physical key, Physical value, PhysicalComparator comparator, Physical[] oldValueBox) {

        return new PhysicalPhysicalTreeMapNodeNonEmpty(key, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getLeft() {
        return EMPTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getRight() {
        return EMPTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Physical get(Physical key, PhysicalComparator comparator) {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean containsKey(Physical key, PhysicalComparator comparator) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean containsValue(Physical value) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void fillKeys(PhysicalSet result) {

    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void fillValues(PhysicalSet result) {

    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toIndentedString(String indent) {
        return "";
    }
}
