/**
 * Associative data structure mapping {@link Physical} keys
 * to {@link Physical} values.
 *
 * <p>Keys are compared using {@link Physical#equals(Object)}.
 * Two keys represent the same key iff they are equal according to
 * {@code equals}.</p>
 *
 * <p>If a new association is inserted for an already existing key,
 * the previous associated value is replaced.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalPhysicalMap {

    /**
     * Associates the specified value with the specified key.
     *
     * <p>If an equal key already exists, its associated value is replaced.</p>
     *
     * @param key the key; {@code key != null}
     * @param value the value; {@code value != null}
     * @return the previously associated value, or {@code null} if none existed
     */
    Physical put(Physical key, Physical value);

    /**
     * Returns the value associated with the specified key.
     *
     * <p>If this map contains a key equal to {@code key},
     * the associated value is returned.</p>
     *
     * @param key the key; {@code key != null}
     * @return the associated value, or {@code null} if the key is not present
     */
    Physical get(Physical key);

    /**
     * Returns whether this map contains a key equal to the specified key
     * (according to {@code equals}).
     *
     * @param key the key; {@code key != null}
     * @return {@code true} if the key exists, otherwise {@code false}
     */
    boolean containsKey(Physical key);

    /**
     * Returns the number of associations currently stored in this map.
     *
     * @return the number of key-value associations
     */
    int size();

    /**
     * Returns whether this map contains no associations.
     *
     * @return {@code true} if this map is empty, otherwise {@code false}
     */
    boolean isEmpty();

    /**
     * Removes all associations from this map.
     */
    void clear();

    /**
     * Returns a set containing all keys currently stored in this map.
     *
     * <p>Each key occurs exactly once in the returned set.</p>
     *
     * <p>The returned set is independent of this map. Structural changes
     * to this map after the method call do not affect the returned set,
     * and vice versa.</p>
     *
     * <p>The contained {@link Physical} objects themselves are not copied.</p>
     *
     * @return a set containing all keys currently stored in this map
     */
    PhysicalSet keySet();

    /**
     * Returns whether this map is equal to the specified object.
     *
     * <p>Two {@code PhysicalPhysicalMap} objects are considered equal iff</p>
     * <ul>
     *   <li>the specified object is also a {@code PhysicalPhysicalMap},</li>
     *   <li>both maps contain the same number of associations, and</li>
     *   <li>for every key contained in this map, the other map contains
     *       an equal key associated with an equal value.</li>
     * </ul>
     *
     * <p>The concrete internal representation and iteration order are irrelevant.</p>
     *
     * @param o the object to compare with
     * @return {@code true} iff the specified object represents an equal map
     */
    @Override
    boolean equals(Object o);

    /**
     * Returns the hash code value of this map.
     *
     * <p>The hash code is computed from the key-value associations stored
     * in this map. Equal maps must have the same hash code.</p>
     *
     * <p>The concrete internal representation and iteration order do not
     * influence the hash code.</p>
     *
     * @return the hash code value of this map
     */
    @Override
    int hashCode();
}