/**
 * A node that can be used by a {@link PhysicalTreeIterator}.
 *
 * <p>This interface abstracts over tree nodes that store {@link Physical}
 * objects and know how to continue a traversal from themselves.</p>
 *
 * <p>The traversal behavior is defined by the implementation of
 * {@link #iter(PhysicalTreeIterator, boolean)}.</p>
 *
 * <p>The iterator traversal is explicitly controlled by the nodes themselves.
 * Implementations may insert additional nodes into the iterator in order
 * to schedule later traversal steps.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalIterableTreeNode {

    /**
     * Updates the traversal state at this node and may return the next
     * {@link Physical} object of the traversal.
     *
     * <p>The parameter {@code next} distinguishes between two situations:</p>
     * <ul>
     *   <li>{@code next == false}: this call initializes traversal of the
     *       subtree rooted at this node. The implementation may insert this
     *       node or other nodes into {@code iterator} in order to schedule
     *       later processing steps.</li>
     *   <li>{@code next == true}: this call processes a node that has already
     *       been scheduled previously. The implementation may return the
     *       stored object and may additionally schedule further traversal
     *       steps by inserting additional nodes into {@code iterator}.</li>
     * </ul>
     *
     * <p>This distinction is required for certain traversal strategies,
     * such as in-order traversal of binary search trees.</p>
     *
     * @param iterator the iterator whose traversal state may be extended;
     *                 {@code iterator != null}
     * @param next indicates whether this is a continuation step
     *             of a previously scheduled node
     * @return the next {@link Physical} object in the traversal,
     *         or {@code null} if this call only updates the traversal state
     */
    Physical iter(PhysicalTreeIterator iterator, boolean next);
}