/**
 * Describes an object that can provide an iterator over {@link Physical}
 * objects.
 *
 * <p>The iterator returns the physical objects one after another in an order
 * defined by the implementing class.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalIterable extends Iterable<Physical> {

    /**
     * Returns an iterator over the physical objects represented by this object.
     *
     * <p>The returned iterator starts before the first element. Repeated calls
     * to {@link PhysicalIterator#next()} return the elements one after another
     * until no further element exists.</p>
     *
     * @return an iterator over the physical objects
     */
    PhysicalIterator iterator();
}