/**
 * Node of a binary search tree storing {@link Physical} key-value pairs.
 *
 * <p>The subtree rooted at such a node is ordered according to a
 * {@link PhysicalComparator}. Search and insertion operations use this
 * order relation to decide whether traversal continues in the left or
 * right subtree.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalPhysicalTreeMapNode {

    /**
     * Returns the left child subtree of this node.
     *
     * <p>The left subtree contains only keys that compare smaller than
     * the key stored in this node according to the comparator used by the
     * surrounding tree map.</p>
     *
     * The returned subtree may be an empty node.
     *
     * @return the left child node (never {@code null}).
     */
    PhysicalPhysicalTreeMapNode getLeft();

    /**
     * Returns the right child subtree of this node.
     *
     * <p>The right subtree contains only keys that compare greater than
     * the key stored in this node according to the comparator used by the
     * surrounding tree map.</p>
     *
     * The returned subtree may be an empty node.
     *
     * @return the right child node (never {@code null}).
     */
    PhysicalPhysicalTreeMapNode getRight();

    /**
     * Inserts the specified key-value association into this subtree.
     *
     * <p>If this subtree already contains a key equal to {@code key},
     * the associated value is replaced by {@code value}. In this case,
     * the previously associated value is written into
     * {@code oldValueBox[0]}.</p>
     *
     * <p>Otherwise, a new node is inserted according to the ordering
     * defined by {@code comparator}. In this case,
     * {@code oldValueBox} remains unchanged.</p>
     *
     * @param key the key to insert; {@code key != null}
     * @param value the associated value; {@code value != null}
     * @param comparator the comparator defining the tree order;
     *                   {@code comparator != null}
     * @param oldValueBox an array of length at least 1 used to return
     *                    the previously associated value, if such a value
     *                    existed; {@code oldValueBox != null}
     * @return the root node of the subtree after insertion
     */
    PhysicalPhysicalTreeMapNode put(
            Physical key,
            Physical value,
            PhysicalComparator comparator,
            Physical[] oldValueBox
    );

    /**
     * Returns the value associated with the specified key.
     *
     * @param key the key to search for; {@code key != null}
     * @param comparator the comparator defining the tree order;
     *                   {@code comparator != null}
     * @return the associated value if this subtree contains an equal key,
     *         otherwise {@code null}
     */
    Physical get(Physical key, PhysicalComparator comparator);

    /**
     * Returns whether this subtree contains a key equal to the specified key.
     *
     * @param key the key to search for; {@code key != null}
     * @param comparator the comparator defining the tree order;
     *                   {@code comparator != null}
     * @return {@code true} iff this subtree contains an equal key
     */
    boolean containsKey(Physical key, PhysicalComparator comparator);

    /**
     * Returns whether this subtree contains a value equal to the specified value.
     *
     * @param value the value to search for; {@code value != null}
     * @return {@code true} iff this subtree contains an equal value
     */
    boolean containsValue(Physical value);

    /**
     * Adds all keys stored in this subtree to the specified set.
     *
     * @param result the set to which keys are added;
     *               {@code result != null}
     */
    void fillKeys(PhysicalSet result);


    /**
     * Adds all values stored in this subtree to the specified set.
     *
     * @param result the set to which values are added;
     *               {@code result != null}
     */
    void fillValues(PhysicalSet result);

    /**
     * Returns a string representation of this subtree using the specified
     * indentation.
     *
     * @param indent the indentation prefix for this node
     * @return a string representation of this subtree
     */
    String toIndentedString(String indent);
}