import java.util.Iterator;

/**
 * Iterator over {@link Physical} objects.
 *
 * <p>An iterator represents the state of an ongoing traversal. It can be used
 * to retrieve physical objects one after another without exposing the internal
 * structure of the underlying data structure.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalIterator extends Iterator<Physical> {

    /**
     * Returns whether another physical object is available.
     *
     * @return {@code true} if a subsequent call to {@link #next()} can return
     *         another object, otherwise {@code false}
     */
    boolean hasNext();

    /**
     * Returns the next physical object of the traversal.
     *
     * <p>If no further object is available, this method returns {@code null}.</p>
     *
     * @return the next physical object, or {@code null} if no further object exists
     */
    Physical next();
}