/**
 * Iterator over tree structures whose nodes implement
 * {@link PhysicalIterableTreeNode}.
 *
 * <p>This iterator does not define a fixed traversal order.
 * Instead, the traversal behavior is determined by the implementation of
 * {@link PhysicalIterableTreeNode#iter(PhysicalTreeIterator, boolean)} in the node classes.</p>
 *
 * <p>The iterator simulates the recursion stack of a traversal using a
 * linked structure of {@code PhysicalTreeIterator} objects.
 * Each instance represents one entry of this simulated stack.</p>
 *
 * <p>The externally visible iterator object always represents the top of the stack.
 * Additional stack entries are created dynamically and linked via the
 * {@code parent} reference.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public class PhysicalTreeIterator implements PhysicalIterator {

    private PhysicalIterableTreeNode node;
    private PhysicalTreeIterator parent;

    /**
     * Creates an empty iterator.
     *
     * <p>An empty iterator represents the end of a traversal.
     * For such an iterator, {@link #hasNext()} returns {@code false}.</p>
     */
    public PhysicalTreeIterator() {
        this.node = null;
        this.parent = null;
    }

    /**
     * Creates a new stack entry for the specified node and inserts it at the
     * front of the stack represented by {@code p}.
     *
     * <p>The object {@code p} remains the externally visible iterator object.
     * Its current state is moved into this newly created object, and {@code p}
     * is updated to store {@code n} as the next node to be processed.</p>
     *
     * <p>This constructor corresponds to a push operation on the simulated stack.</p>
     *
     * @param n the node to be processed next; {@code n != null}
     * @param p the iterator whose simulated stack is extended; {@code p != null}
     */
    public PhysicalTreeIterator(PhysicalIterableTreeNode n,
                                PhysicalTreeIterator p) {

        this.node = p.node;
        this.parent = p.parent;

        p.node = n;
        p.parent = this;
    }

    /**
     * Returns whether another element is available.
     *
     * @return {@code true} if a subsequent call to {@link #next()} can return
     *         another element, otherwise {@code false}
     */
    @Override
    public boolean hasNext() {
        return node != null;
    }

    /**
     * Returns the next element of the traversal.
     *
     * <p>This method removes the top node from the simulated stack
     * and then calls {@link PhysicalIterableTreeNode#iter(PhysicalTreeIterator, boolean)}
     * on that node.</p>
     *
     * <p>The node returns its stored {@link Physical} object and prepares
     * the iterator for the subsequent traversal steps by inserting further
     * nodes into the stack.</p>
     *
     * <p>If no further element exists, {@code null} is returned.</p>
     *
     * @return the next {@link Physical} object, or {@code null} if no further
     *         element exists
     */
    @Override
    public Physical next() {

        if (node == null) {
            return null;
        }

        PhysicalIterableTreeNode todo = node;

        // pop operation
        node = parent.node;
        parent = parent.parent;

        return todo.iter(this, true);
    }
}