/**
 * A node that can be used by a {@link PhysicalTreeIterator}.
 *
 * <p>This interface abstracts over tree nodes that store {@link Physical}
 * objects and know how to continue a traversal from themselves.</p>
 *
 * <p>The traversal behavior is defined by the implementation of
 * {@link #iter(PhysicalTreeIterator, boolean)}.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalIterableTreeNode {

    /**
     * Continues the traversal at this node and returns a {@link Physical} object.
     *
     * <p>The parameter {@code next} distinguishes between two situations:</p>
     * <ul>
     *   <li>{@code next == false}: this call initializes traversal of the subtree
     *   rooted at this node</li>
     *   <li>{@code next == true}: this call continues traversal after this node
     *       has already been (partially) processed</li>
     * </ul>
     *
     * <p>This distinction is required for certain traversal strategies,
     * such as in-order traversal of binary search trees.</p>
     *
     * <p>The implementation may insert further nodes into the iterator
     * to continue traversal.</p>
     *
     * @param iterator the iterator whose traversal state may be extended;
     *                 {@code iterator != null}
     * @param next indicates whether this is a continuation step
     *             (the node has already been processed)
     * @return the next {@link Physical} object in the traversal
     */
    Physical iter(PhysicalTreeIterator iterator, boolean next);
}